# Generated by Django 3.1.5 on 2021-02-21 02:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('driver_id', models.PositiveIntegerField()),
                ('licence_plate', models.CharField(max_length=30)),
                ('passenger_list', models.TextField(default='[]')),
                ('current_lat', models.FloatField(default=38.2393)),
                ('current_long', models.FloatField(default=-85.7598)),
                ('route', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('sunet', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_loc', models.CharField(max_length=30)),
                ('current_lat', models.FloatField(default=38.2393)),
                ('current_long', models.FloatField(default=-85.7598)),
                ('dest_loc', models.CharField(max_length=30)),
                ('dest_lat', models.FloatField(default=37.4254)),
                ('dest_long', models.FloatField(default=-122.1629)),
                ('num_passengers', models.IntegerField(default=1)),
                ('safety_lvl', models.PositiveIntegerField(default=5)),
                ('priority', models.FloatField(default=50)),
                ('time_requested', models.DateTimeField(default=datetime.datetime.now, verbose_name='time requested')),
                ('picked_up', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), null=True)),
                ('dropped_off', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), null=True)),
                ('assigned', models.IntegerField(default=-1)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dispatcher_controller.driver')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dispatcher_controller.student')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dispatcher_controller.student'),
        ),
    ]
